### ISSUE TITLE
from collections import MutableMapping

### ISSUE THREAD

**Issue by drgrib** [google/grumpy#238] opened 2017-02-06 22:32 UTC
`go build` chokes on transcompiled `.py` source importing this line

`from collections import MutableMapping`

with a `cannot find package` error:

```
languageTest.go:5:2: cannot find package "grumpy/lib/collections/MutableMapping" in any of:
...
make: *** [languageTest] Error 1
```

So this is another feature of `collections` that is not implemented, despite `collections` being listed as finished except for `namedtuple` in the [Missing features page](https://github.com/google/grumpy/wiki/Missing-Features).

**Comment by trotterdylan** [comment] 2017-02-06 22:49
Although it's not obvious, this is actually a duplicate of https://github.com/google/grumpy/issues/99

**Closed by trotterdylan** 2017-02-06 22:49 UTC

**Comment by drgrib** [comment] 2017-02-06 22:51
@trotterdylan Glad to hear that it is already on your radar and that the fix will be so generalizable.
