### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by S-YOU** [google/grumpy#252] opened 2017-02-16 02:51 UTC
This is also triggered when I try to add a test on test_datetime.py.

```
test_comparing (__main__.TestTime) ... panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x2c8d92]

goroutine 1 [running]:
panic(0xc26060, 0xc42000a0c0)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
grumpy.(*dictTable).loadUsed(0x0, 0x0)
	/path/to/grumpy/build/src/grumpy/dict.go:96 +0x22
grumpy.(*Dict).Len(0xc4202677c0, 0xc42022ec00)
	/path/to/grumpy/build/src/grumpy/dict.go:388 +0x39
grumpy.dictsAreEqual(0xc420430930, 0xc42022ec00, 0xc4202677c0, 0xff, 0xc4200e2100)
	/path/to/grumpy/build/src/grumpy/dict.go:494 +0x172
grumpy.dictNE(0xc420430930, 0xc42022ec00, 0xc4202677c0, 0x2c17e3, 0xc420430930)
	/path/to/grumpy/build/src/grumpy/dict.go:711 +0x66
grumpy.tryRichCompare(0xc420430930, 0x3, 0xc42022ec00, 0xc4202677c0, 0x6, 0x0)
	/path/to/grumpy/build/src/grumpy/core.go:1056 +0x12c
grumpy.compareRich(0xc420430930, 0x3, 0xc42022ec00, 0xc4202677c0, 0x101b520, 0x0)
	/path/to/grumpy/build/src/grumpy/core.go:987 +0x4d
grumpy.NE(0xc420430930, 0xc42022ec00, 0xc4202677c0, 0x2, 0x0)
	/path/to/grumpy/build/src/grumpy/core.go:604 +0x4c
main.initModule.func13.4(0xc420430930, 0xc420179f50, 0x1, 0x6, 0x6, 0xc420029680)
	/path/to/grumpy/a.go:29609 +0x6409
grumpy.(*Code).Eval(0xc420215f80, 0xc4204308c0, 0xc4202def00, 0xc420029680, 0x1, 0x1, 0x0, 0x0, 0x0, 0xc420462000, ...)
	/path/to/grumpy/build/src/grumpy/code.go:66 +0x188
grumpy.functionCall(0xc4204308c0, 0xc42033b380, 0xc420029680, 0x1, 0x1, 0x0, 0x0, 0x0, 0xc420029680, 0x0)
	/path/to/grumpy/build/src/grumpy/function.go:121 +0x9a
grumpy.(*Object).Call(0xc42033b380, 0xc4204308c0, 0xc420029680, 0x1, 0x1, 0x0, 0x0, 0x0, 0x101b2f0, 0x0)
	/path/to/grumpy/build/src/grumpy/object.go:64 +0xa3
grumpy.methodCall(0xc4204308c0, 0xc42036cb00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x101b2f0, 0x0)
	/path/to/grumpy/build/src/grumpy/method.go:68 +0x253
grumpy.(*Object).Call(0xc42036cb00, 0xc4204308c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x101b2f0, 0x0)
	/path/to/grumpy/build/src/grumpy/object.go:64 +0xa3
grumpy/lib/unittest_case.initModule.func11.18(0xc4204308c0, 0xc420178330, 0x2, 0x6, 0x6, 0xc42016a050)
	/path/to/grumpy/build/src/grumpy/lib/unittest_case/module.go:3334 +0x30fc
grumpy.(*Code).Eval(0xc42028c5a0, 0xc420430850, 0xc42013ea40, 0xc42016a050, 0x2, 0x2, 0x1038c80, 0x0, 0x0, 0xc420462000, ...)
	/path/to/grumpy/build/src/grumpy/code.go:66 +0x188
grumpy.functionCall(0xc420430850, 0xc4201c3140, 0xc42016a050, 0x2, 0x2, 0x1038c80, 0x0, 0x0, 0xc42016a058, 0xc420267640)
	/path/to/grumpy/build/src/grumpy/function.go:121 +0x9a
grumpy.(*Object).Call(0xc4201c3140, 0xc420430850, 0xc42016a050, 0x2, 0x2, 0x1038c80, 0x0, 0x0, 0x0, 0xc42025f818)
	/path/to/grumpy/build/src/grumpy/object.go:64 +0xa3
grumpy.methodCall(0xc420430850, 0xc42036c680, 0xc4200295f0, 0x1, 0x1, 0x1038c80, 0x0, 0x0, 0xc420267640, 0xc420075340)
	/path/to/grumpy/build/src/grumpy/method.go:68 +0x253
grumpy.(*Object).Call(0xc42036c680, 0xc420430850, 0xc4200295f0, 0x1, 0x1, 0x1038c80, 0x0, 0x0, 0xc420430850, 0xc42039bf00)
	/path/to/grumpy/build/src/grumpy/object.go:64 +0xa3
grumpy.Invoke(0xc420430850, 0xc42036c680, 0xc4200295f0, 0x1, 0x1, 0xc4205f3140, 0x1038c80, 0x0, 0x0, 0xc42036c640, ...)
	/path/to/grumpy/build/src/grumpy/core.go:599 +0xd8
grumpy/lib/unittest_case.initModule.func11.20(0xc420430850, 0xc42015c3c0, 0x3, 0x8, 0x8, 0xc42016a040)
	/path/to/grumpy/build/src/grumpy/lib/unittest_case/module.go:4287 +0x294
grumpy.(*Code).Eval(0xc42028c660, 0xc420247c00, 0xc42013ea40, 0xc42016a040, 0x2, 0x2, 0x0, 0x0, 0x0, 0xc420462000, ...)
	/path/to/grumpy/build/src/grumpy/code.go:66 +0x188
grumpy.functionCall(0xc420247c00, 0xc4201c32c0, 0xc42016a040, 0x2, 0x2, 0x0, 0x0, 0x0, 0xc42016a048, 0x0)
	/path/to/grumpy/build/src/grumpy/function.go:121 +0x9a
grumpy.(*Object).Call(0xc4201c32c0, 0xc420247c00, 0xc42016a040, 0x2, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0)
	/path/to/grumpy/build/src/grumpy/object.go:64 +0xa3
grumpy.(*callSlot).wrapCallable.func1(0xc420247c00, 0xc42039bf00, 0xc42012c210, 0x1, 0x6, 0x0, 0x0, 0x0, 0x101b520, 0x0)
	/path/to/grumpy/build/src/grumpy/slots.go:92 +0x153
grumpy.(*Object).Call(0xc42039bf00, 0xc420247c00, 0xc42012c210, 0x1, 0x6, 0x0, 0x0, 0x0, 0x101b520, 0x0)
	/path/to/grumpy/build/src/grumpy/object.go:64 +0xa3
grumpy/lib/unittest_suite.initModule.func3.1(0xc420247c00, 0xc420475640, 0x3, 0x8, 0x8, 0xc4202d7260)
	/path/to/grumpy/build/src/grumpy/lib/unittest_suite/module.go:1576 +0x173f
grumpy.(*Code).Eval(0xc420472b40, 0xc420247b90, 0xc420372000, 0xc4202d7260, 0x2, 0x2, 0x1038c80, 0x0, 0x0, 0xc420462000, ...)
	/path/to/grumpy/build/src/grumpy/code.go:66 +0x188
grumpy.functionCall(0xc420247b90, 0xc420372b00, 0xc4202d7260, 0x2, 0x2, 0x1038c80, 0x0, 0x0, 0xc4202d7268, 0xc42036bbe0)
	/path/to/grumpy/build/src/grumpy/function.go:121 +0x9a
grumpy.(*Object).Call(0xc420372b00, 0xc420247b90, 0xc4202d7260, 0x2, 0x2, 0x1038c80, 0x0, 0x0, 0x0, 0xc420260158)
	/path/to/grumpy/build/src/grumpy/object.go:64 +0xa3
grumpy.methodCall(0xc420247b90, 0xc420512c80, 0xc420028d58, 0x1, 0x1, 0x1038c80, 0x0, 0x0, 0xc42036bbe0, 0xc420075340)
	/path/to/grumpy/build/src/grumpy/method.go:68 +0x253
grumpy.(*Object).Call(0xc420512c80, 0xc420247b90, 0xc420028d58, 0x1, 0x1, 0x1038c80, 0x0, 0x0, 0xc420247b90, 0xc4201c9ea0)
	/path/to/grumpy/build/src/grumpy/object.go:64 +0xa3
grumpy.Invoke(0xc420247b90, 0xc420512c80, 0xc420028d58, 0x1, 0x1, 0xc4200eee70, 0x1038c80, 0x0, 0x0, 0xc420512c40, ...)
	/path/to/grumpy/build/src/grumpy/core.go:599 +0xd8
grumpy/lib/unittest_suite.initModule.func2.10(0xc420247b90, 0xc420475b80, 0x3, 0x8, 0x8, 0xc4202d7250)
	/path/to/grumpy/build/src/grumpy/lib/unittest_suite/module.go:1111 +0x294
grumpy.(*Code).Eval(0xc4204729c0, 0xc42004d1f0, 0xc420372000, 0xc4202d7250, 0x2, 0x2, 0x0, 0x0, 0x0, 0xc420462000, ...)
	/path/to/grumpy/build/src/grumpy/code.go:66 +0x188
grumpy.functionCall(0xc42004d1f0, 0xc420372900, 0xc4202d7250, 0x2, 0x2, 0x0, 0x0, 0x0, 0xc4202d7258, 0x0)
	/path/to/grumpy/build/src/grumpy/function.go:121 +0x9a
grumpy.(*Object).Call(0xc420372900, 0xc42004d1f0, 0xc4202d7250, 0x2, 0x2, 0x0, 0x0, 0x0, 0x6, 0x0)
	/path/to/grumpy/build/src/grumpy/object.go:64 +0xa3
grumpy.(*callSlot).wrapCallable.func1(0xc42004d1f0, 0xc4201c9ea0, 0xc42012c150, 0x1, 0x6, 0x0, 0x0, 0x0, 0x101b520, 0x0)
	/path/to/grumpy/build/src/grumpy/slots.go:92 +0x153
grumpy.(*Object).Call(0xc4201c9ea0, 0xc42004d1f0, 0xc42012c150, 0x1, 0x6, 0x0, 0x0, 0x0, 0x101b520, 0x0)
	/path/to/grumpy/build/src/grumpy/object.go:64 +0xa3
grumpy/lib/unittest_suite.initModule.func3.1(0xc42004d1f0, 0xc4203784b0, 0x3, 0x6, 0x6, 0xc4202d6b80)
	/path/to/grumpy/build/src/grumpy/lib/unittest_suite/module.go:1576 +0x173f
grumpy.(*Code).Eval(0xc420472b40, 0xc42004d180, 0xc420372000, 0xc4202d6b80, 0x2, 0x2, 0x1038c80, 0x0, 0x0, 0xc42002a800, ...)
	/path/to/grumpy/build/src/grumpy/code.go:66 +0x188
grumpy.functionCall(0xc42004d180, 0xc420372b00, 0xc4202d6b80, 0x2, 0x2, 0x1038c80, 0x0, 0x0, 0xc4202d6b88, 0xc4202f7640)
	/path/to/grumpy/build/src/grumpy/function.go:121 +0x9a
grumpy.(*Object).Call(0xc420372b00, 0xc42004d180, 0xc4202d6b80, 0x2, 0x2, 0x1038c80, 0x0, 0x0, 0x0, 0xc4201a0ab8)
	/path/to/grumpy/build/src/grumpy/object.go:64 +0xa3
grumpy.methodCall(0xc42004d180, 0xc4204a21c0, 0xc4200298f8, 0x1, 0x1, 0x1038c80, 0x0, 0x0, 0xc4202f7640, 0xc420075340)
	/path/to/grumpy/build/src/grumpy/method.go:68 +0x253
grumpy.(*Object).Call(0xc4204a21c0, 0xc42004d180, 0xc4200298f8, 0x1, 0x1, 0x1038c80, 0x0, 0x0, 0xc42004d180, 0xc4202f6fc0)
	/path/to/grumpy/build/src/grumpy/object.go:64 +0xa3
grumpy.Invoke(0xc42004d180, 0xc4204a21c0, 0xc4200298f8, 0x1, 0x1, 0xc42020f380, 0x1038c80, 0x0, 0x0, 0xc4204a2180, ...)
	/path/to/grumpy/build/src/grumpy/core.go:599 +0xd8
grumpy/lib/unittest_suite.initModule.func2.10(0xc42004d180, 0xc4203783f0, 0x3, 0x6, 0x6, 0xc4202d6b70)
	/path/to/grumpy/build/src/grumpy/lib/unittest_suite/module.go:1111 +0x294
grumpy.(*Code).Eval(0xc4204729c0, 0xc42004d110, 0xc420372000, 0xc4202d6b70, 0x2, 0x2, 0x0, 0x0, 0x0, 0xc42002a800, ...)
	/path/to/grumpy/build/src/grumpy/code.go:66 +0x188
grumpy.functionCall(0xc42004d110, 0xc420372900, 0xc4202d6b70, 0x2, 0x2, 0x0, 0x0, 0x0, 0xc4202d6b78, 0x0)
	/path/to/grumpy/build/src/grumpy/function.go:121 +0x9a
grumpy.(*Object).Call(0xc420372900, 0xc42004d110, 0xc4202d6b70, 0x2, 0x2, 0x0, 0x0, 0x0, 0x6, 0x0)
	/path/to/grumpy/build/src/grumpy/object.go:64 +0xa3
grumpy.(*callSlot).wrapCallable.func1(0xc42004d110, 0xc4202f6fc0, 0xc42011c930, 0x1, 0x6, 0x0, 0x0, 0x0, 0x101b520, 0x0)
	/path/to/grumpy/build/src/grumpy/slots.go:92 +0x153
grumpy.(*Object).Call(0xc4202f6fc0, 0xc42004d110, 0xc42011c930, 0x1, 0x6, 0x0, 0x0, 0x0, 0x101b520, 0x0)
	/path/to/grumpy/build/src/grumpy/object.go:64 +0xa3
grumpy/lib/unittest_suite.initModule.func3.1(0xc42004d110, 0xc42011c900, 0x3, 0x6, 0x6, 0xc4202d6b50)
	/path/to/grumpy/build/src/grumpy/lib/unittest_suite/module.go:1576 +0x173f
grumpy.(*Code).Eval(0xc420472b40, 0xc42004cf50, 0xc420372000, 0xc4202d6b50, 0x2, 0x2, 0x1038c80, 0x0, 0x0, 0xc42002a800, ...)
	/path/to/grumpy/build/src/grumpy/code.go:66 +0x188
grumpy.functionCall(0xc42004cf50, 0xc420372b00, 0xc4202d6b50, 0x2, 0x2, 0x1038c80, 0x0, 0x0, 0xc4202d6b58, 0xc4202f7600)
	/path/to/grumpy/build/src/grumpy/function.go:121 +0x9a
grumpy.(*Object).Call(0xc420372b00, 0xc42004cf50, 0xc4202d6b50, 0x2, 0x2, 0x1038c80, 0x0, 0x0, 0x0, 0xc4201a13f8)
	/path/to/grumpy/build/src/grumpy/object.go:64 +0xa3
grumpy.methodCall(0xc42004cf50, 0xc4204a2040, 0xc4200298d8, 0x1, 0x1, 0x1038c80, 0x0, 0x0, 0xc4202f7600, 0xc420075340)
	/path/to/grumpy/build/src/grumpy/method.go:68 +0x253
grumpy.(*Object).Call(0xc4204a2040, 0xc42004cf50, 0xc4200298d8, 0x1, 0x1, 0x1038c80, 0x0, 0x0, 0xc42004cf50, 0xc4204bc920)
	/path/to/grumpy/build/src/grumpy/object.go:64 +0xa3
grumpy.Invoke(0xc42004cf50, 0xc4204a2040, 0xc4200298d8, 0x1, 0x1, 0xc42020f260, 0x1038c80, 0x0, 0x0, 0xc4204a2000, ...)
	/path/to/grumpy/build/src/grumpy/core.go:599 +0xd8
grumpy/lib/unittest_suite.initModule.func2.10(0xc42004cf50, 0xc420114540, 0x3, 0x6, 0x6, 0xc4202d6b40)
	/path/to/grumpy/build/src/grumpy/lib/unittest_suite/module.go:1111 +0x294
grumpy.(*Code).Eval(0xc4204729c0, 0xc42004cee0, 0xc420372000, 0xc4202d6b40, 0x2, 0x2, 0x0, 0x0, 0x0, 0xc42002a800, ...)
	/path/to/grumpy/build/src/grumpy/code.go:66 +0x188
grumpy.functionCall(0xc42004cee0, 0xc420372900, 0xc4202d6b40, 0x2, 0x2, 0x0, 0x0, 0x0, 0xc4202d6b48, 0x101b2f0)
	/path/to/grumpy/build/src/grumpy/function.go:121 +0x9a
grumpy.(*Object).Call(0xc420372900, 0xc42004cee0, 0xc4202d6b40, 0x2, 0x2, 0x0, 0x0, 0x0, 0x2ca19f, 0xc42049aa50)
	/path/to/grumpy/build/src/grumpy/object.go:64 +0xa3
grumpy.(*callSlot).wrapCallable.func1(0xc42004cee0, 0xc4204bc920, 0xc420114510, 0x1, 0x6, 0x0, 0x0, 0x0, 0xc4202d6b28, 0x0)
	/path/to/grumpy/build/src/grumpy/slots.go:92 +0x153
grumpy.(*Object).Call(0xc4204bc920, 0xc42004cee0, 0xc420114510, 0x1, 0x6, 0x0, 0x0, 0x0, 0x101b2f0, 0x0)
	/path/to/grumpy/build/src/grumpy/object.go:64 +0xa3
grumpy/lib/unittest_runner.initModule.func3.3(0xc42004cee0, 0xc4204a1cc0, 0x2, 0x7, 0x7, 0xc4202d6b10)
	/path/to/grumpy/build/src/grumpy/lib/unittest_runner/module.go:2609 +0x7bcd
grumpy.(*Code).Eval(0xc42047e720, 0xc42004ce70, 0xc420426400, 0xc4202d6b10, 0x2, 0x2, 0x0, 0x0, 0x0, 0xc42002a800, ...)
	/path/to/grumpy/build/src/grumpy/code.go:66 +0x188
grumpy.functionCall(0xc42004ce70, 0xc42010ff00, 0xc4202d6b10, 0x2, 0x2, 0x0, 0x0, 0x0, 0xc4202d6b18, 0xc42013dd01)
	/path/to/grumpy/build/src/grumpy/function.go:121 +0x9a
grumpy.(*Object).Call(0xc42010ff00, 0xc42004ce70, 0xc4202d6b10, 0x2, 0x2, 0x0, 0x0, 0x0, 0x2f8a1d, 0xc42004ce70)
	/path/to/grumpy/build/src/grumpy/object.go:64 +0xa3
grumpy.methodCall(0xc42004ce70, 0xc4204a1d80, 0xc4204338c0, 0x1, 0x7, 0x0, 0x0, 0x0, 0xc4202f70a0, 0x0)
	/path/to/grumpy/build/src/grumpy/method.go:68 +0x253
grumpy.(*Object).Call(0xc4204a1d80, 0xc42004ce70, 0xc4204338c0, 0x1, 0x7, 0x0, 0x0, 0x0, 0xc4202f70a0, 0x0)
	/path/to/grumpy/build/src/grumpy/object.go:64 +0xa3
grumpy/lib/test/test_support.initModule.func12(0xc42004ce70, 0xc4201144b0, 0x1, 0x6, 0x6, 0xc420114480)
	/path/to/grumpy/build/src/grumpy/lib/test/test_support/module.go:2867 +0x6a7
grumpy.(*Code).Eval(0xc4204738c0, 0xc420430000, 0xc42011a3c0, 0xc420114480, 0x1, 0x6, 0x0, 0x0, 0x0, 0xc420344fc0, ...)
	/path/to/grumpy/build/src/grumpy/code.go:66 +0x188
grumpy.functionCall(0xc420430000, 0xc4203b0180, 0xc420114480, 0x1, 0x6, 0x0, 0x0, 0x0, 0x2c2164, 0xc420430000)
	/path/to/grumpy/build/src/grumpy/function.go:121 +0x9a
grumpy.(*Object).Call(0xc4203b0180, 0xc420430000, 0xc420114480, 0x1, 0x6, 0x0, 0x0, 0x0, 0x101b2f0, 0x0)
	/path/to/grumpy/build/src/grumpy/object.go:64 +0xa3
grumpy/lib/test/test_support.initModule.func13(0xc420430000, 0xc4204b2280, 0x1, 0x8, 0x8, 0xc4204aee60)
	/path/to/grumpy/build/src/grumpy/lib/test/test_support/module.go:3362 +0x1f25
grumpy.(*Code).Eval(0xc420473920, 0xc4200a9f80, 0xc42011a3c0, 0xc4204aee60, 0x1, 0x9, 0x0, 0x0, 0x0, 0x2c17e3, ...)
	/path/to/grumpy/build/src/grumpy/code.go:66 +0x188
grumpy.functionCall(0xc4200a9f80, 0xc4203b1200, 0xc4204aee60, 0x1, 0x9, 0x0, 0x0, 0x0, 0x26d77d, 0xc4204aee60)
	/path/to/grumpy/build/src/grumpy/function.go:121 +0x9a
grumpy.(*Object).Call(0xc4203b1200, 0xc4200a9f80, 0xc4204aee60, 0x1, 0x9, 0x0, 0x0, 0x0, 0x101be40, 0xc4202def00)
	/path/to/grumpy/build/src/grumpy/object.go:64 +0xa3
main.initModule.func21(0xc4200a9f80, 0x0, 0x0, 0x0, 0x0, 0x0)
	/path/to/grumpy/a.go:56108 +0x267
grumpy.(*Code).Eval(0xc4204b64e0, 0xc4200a8070, 0xc4202def00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc420494000, ...)
	/path/to/grumpy/build/src/grumpy/code.go:66 +0x188
grumpy.functionCall(0xc4200a8070, 0xc4204b3780, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc4200a8070, 0x2)
	/path/to/grumpy/build/src/grumpy/function.go:121 +0x9a
grumpy.(*Object).Call(0xc4204b3780, 0xc4200a8070, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc4204bc8e0, 0xc4204b64e0)
	/path/to/grumpy/build/src/grumpy/object.go:64 +0xa3
main.initModule(0xc4200a8070, 0x0, 0x0, 0x0, 0x0, 0x0)
	/path/to/grumpy/a.go:56140 +0x12e8d
grumpy.(*Code).Eval(0xc4200a7560, 0xc4200a8000, 0xc4202def00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x26ce08, ...)
	/path/to/grumpy/build/src/grumpy/code.go:66 +0x188
grumpy.RunMain(0xc4200a7560, 0x0)
	/path/to/grumpy/build/src/grumpy/module.go:294 +0x1f8
main.main()
	/path/to/grumpy/a.go:56152 +0xa5
  ```

**Comment by trotterdylan** [comment] 2017-02-16 17:37
Thanks for the report. This is a shot in the dark but the only thing that's changed in dict recently is c7f97e72452ff91b906c9edabdec0024e9078470. Would you mind trying to revert that locally and see if it fixes?

**Comment by S-YOU** [comment] 2017-02-17 02:40
Seems like this is occuring on same place as #251 
```
if πTemp006, πE = πg.NE(πF, µbadarg, µt1); πE != nil {
```
I havn't try to check 37f97e7 but tests causing this is on this block 
https://github.com/google/grumpy/blob/master/third_party/stdlib/test/test_datetime.py#L1753

**Comment by S-YOU** [comment] 2017-02-17 03:12
I tried to revert c7f97e72452ff91b906c9edabdec0024e9078470, it remains the same.

**Comment by trotterdylan** [comment] 2017-02-18 22:35
I'm fairly certain this is a duplicate of https://github.com/google/grumpy/issues/251

**Closed by trotterdylan** 2017-02-18 22:35 UTC
Labels: duplicate
